#To run Vagrant for Ubuntu VM with VMware Workstation Environment:

Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2204"
    config.vm.provider "vmware_desktop" do |vb|
      vb.gui = true
      end
  end